name: emergency_call_v2
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  awesome_bottom_bar: ^1.2.4
  cloud_firestore: ^4.8.4
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.0+1
  flutter_smart_dialog: ^4.9.4
  flutter_svg: ^2.0.7
  get: ^4.6.5
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.4.0
  http: ^1.1.0
  location: ^5.0.3

  logger: ^2.0.1
  url_launcher: ^6.1.12
  velocity_x: ^4.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
